# Generated by Django 5.1 on 2024-08-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clue',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='file_size',
        ),
    ]
