# Generated by Django 5.1 on 2024-08-15 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_clue_file_size_remove_puzzle_file_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='user',
            new_name='user_id',
        ),
    ]
