# Generated by Django 5.1 on 2024-08-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_rename_user_puzzle_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='user_id',
            new_name='user',
        ),
    ]
