# Generated by Django 5.1 on 2024-08-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_rename_user_id_puzzle_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clue',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='clues/'),
        ),
    ]
